# Generated by Django 2.2.6 on 2019-12-15 13:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('art_id', models.AutoField(primary_key=True, serialize=False)),
                ('art_name', models.CharField(max_length=100)),
                ('art_slug', models.SlugField(unique=True)),
                ('cat_id', models.IntegerField(choices=[(1, 'Tin bóng đá'), (2, 'soi cầu'), (3, 'soi kèo nhà cái'), (4, 'video bóng đá'), (5, 'sổ mơ'), (6, 'giải mã giấc mơ'), (7, 'hướng dẫn')])),
                ('art_img', models.ImageField(max_length=255, upload_to='')),
                ('art_mo_ta', models.CharField(default='mô tả ngắn gọn', max_length=150)),
                ('description', ckeditor.fields.RichTextField()),
                ('status', models.SmallIntegerField(choices=[(1, 'hiện'), (0, 'ẩn')])),
                ('date_create', models.DateField()),
            ],
            options={
                'db_table': 'tbl_Product',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'hiện'), (0, 'ẩn')])),
                ('date_create', models.DateField()),
            ],
            options={
                'db_table': 'tbl_Category',
                'unique_together': {('cat_name', 'slug')},
            },
        ),
    ]
