# Generated by Django 2.2.6 on 2019-12-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
